CREATE TABLE IF NOT EXISTS nyc_taxi_trips (
    VendorID INTEGER,
    tpep_pickup_datetime TIMESTAMP,
    tpep_dropoff_datetime TIMESTAMP,
    passenger_count BIGINT,
    trip_distance DOUBLE PRECISION,
    PULocationID INTEGER,
    DOLocationID INTEGER,
    payment_type BIGINT,
    fare_amount DOUBLE PRECISION,
    extra DOUBLE PRECISION,
    mta_tax DOUBLE PRECISION,
    tip_amount DOUBLE PRECISION,
    tolls_amount DOUBLE PRECISION,
    total_amount DOUBLE PRECISION,
    trip_duration_sec BIGINT,
    average_speed_mph DOUBLE PRECISION,
    trip_category VARCHAR(255),
    pickup_hour INTEGER,
    day_of_week INTEGER,
    month INTEGER,
    is_weekend VARCHAR(255),
    Borough VARCHAR(255),
    Zone VARCHAR(255)
);
